### PR TITLE
Add configurable screensaver mode

### PR DESCRIPTION
**Pull request by mcauley-penney**
This PR adds the ability for the user to summon `the duck` after a configurable quantity of minutes

### CODE REVIEW

**Comment by tamton-aquib** [comment]
Hi, sorry for being inactive.

I don't know if we should be keeping a screensaver feature in a toy plugin like this 😅 .
Also I feel like we could just set something like:
```vim
autocmd VimEnter * lua vim.defer_fn(require('duck').hatch, 2000)
```

**Comment by tamton-aquib** [comment]
let me know your thoughts 😄

**Comment by mcauley-penney** [comment]
No worries! Before submitting the PR, I honestly felt like it wasn't a good fit but I figured I'd show it anyway. 

I'm attempting to add some features, like destroying the current buffer and teaching the "screensaver" to interact with other windows that are intended as destroyable (imagine creating the duck and some algae, and the duck eats the algae as it waddles over it), but those are for my own personal enjoyment. 

It is safe to close this PR. Thanks!

**Comment by tamton-aquib** [comment]
> imagine creating the duck and some algae, and the duck eats the algae as it waddles over it

Haha one of my friends suggested something similar 😄 
he also asked about using the cursor to cook the ducks.

> It is safe to close this PR. Thanks!

👍🏻

**Pull request closed without merging**
