### PR TITLE
Allow the hatch function to accept a speed parameter

### PR DESCRIPTION
**Pull request by Molter73**
A small change that allows hatched ducks to move at different speeds.

### CODE REVIEW

**Comment by tamton-aquib** [comment]
Heyyo @Molter73 , thats a nice addition thanks.
Although we'll have to specify in the README that slower the speed, faster the duck.
Let me know if you can, or I'll add it in next commit.

**Comment by Molter73** [comment]
Now that you mention it, it does seem weird that lower speed = faster movement, let me see if I can either:
- Get the reciprocate (so that faster speed is faster movement).
- Rename the parameter to something other than speed.
- If all else fails, add the entry in the README.

**Comment by Molter73** [comment]
@tamton-aquib, I changed the speed argument to be steps/second, a step being move once. Think you could take another look?

**Comment by tamton-aquib** [comment]
Ah, sorry it took time, i thought the pr was not finished. 😅 

Just checked, works fine. Thanks again.

**Pull request merged**
